### ISSUE TITLE
pyodbc interface error when opening the export tool - see attached image

### ISSUE THREAD

**Issue by ujvalak** [nhrap-dev/export#11]
![pyodbc_interaface_error_ExportTool](https://user-images.githubusercontent.com/10346175/88830755-3f3b6700-d183-11ea-8ac2-8ec7e2bf8f87.png)

**Comment by clindeman** [comment]
This may be related to the hardcoded single driver 'ODBC Driver 11 for SQL Server' under hazpy/legacy/common/def getStudyRegions(): 

Perhaps changing it to match the drivers list in class HazusDB(): / def createConnection(self): in the same file may resolve the issue.

Changing it to 17 from 11 the tool opened but selecting my one Study Region Nueces TX resulted in an error: "Unable to initialize the Study Region. Please select another Study Region to continue. Error: <class 'Exception'>"

**Comment by clindeman** [comment]
Fixed in version 1.0.1
